In [4]:
import os
import glob
import pandas as pd

切换工作目录到fastq

In [3]:
os.chdir('../../fastq')
os.listdir()[:3]
# TSN20211217-010-00177_28D_20211221-BAN8_H05_H05_i62.R1.fq.gz

['TSN20220226-010-00090_44_20220226-BAN23_D06_D06_i89.R1.fq.gz',
 'TSN20220226-010-00090_14_20220226-BAN23_F02_F02_i89.R2.fq.gz',
 'WT-ND6-rep1_R2.fastq']

In [21]:
df = pd.DataFrame(sorted(glob.glob('TSN*.fq.gz')), columns=['raw_name'])
df.head(2)

                                            raw_name
0  TSN20220226-010-00090_10_20220226-BAN23_B02_B0...
1  TSN20220226-010-00090_10_20220226-BAN23_B02_B0...

In [22]:
df['idx'] = df.raw_name.map(lambda x: x.split('_')[1]).map(int)
df

                                             raw_name  idx
0   TSN20220226-010-00090_10_20220226-BAN23_B02_B0...   10
1   TSN20220226-010-00090_10_20220226-BAN23_B02_B0...   10
2   TSN20220226-010-00090_11_20220226-BAN23_C02_C0...   11
3   TSN20220226-010-00090_11_20220226-BAN23_C02_C0...   11
4   TSN20220226-010-00090_12_20220226-BAN23_D02_D0...   12
..                                                ...  ...
89  TSN20220226-010-00090_7_20220226-BAN23_G01_G01...    7
90  TSN20220226-010-00090_8_20220226-BAN23_H01_H01...    8
91  TSN20220226-010-00090_8_20220226-BAN23_H01_H01...    8
92  TSN20220226-010-00090_9_20220226-BAN23_A02_A02...    9
93  TSN20220226-010-00090_9_20220226-BAN23_A02_A02...    9

[94 rows x 2 columns]

In [25]:
df_name = pd.read_excel('../snakepipes_target-seq/for_1.5generation/lib.xlsx')
df_name['idx'] = df_name.idx.map(int)
df_name.head()

   idx        region_id                  lib_name       anno
0    1  ND5.1-on-target        WT-ND5.1-rep1-0301  SupFig22b
1    2  ND5.1-on-target        WT-ND5.1-rep2-0301  SupFig22b
2    3  ND5.1-on-target  TALE-NES-ND5.1-rep1-0301  SupFig22b
3    4  ND5.1-on-target  TALE-NES-ND5.1-rep2-0301  SupFig22b
4    5  ND5.1-on-target  DddA-NES-ND5.1-rep1-0301  SupFig22b

In [26]:
df_merge = df.merge(df_name, on='idx', how='left')
df_merge

,raw_name,idx,region_id,lib_name,anno
0,TSN20220226-010-00090_10_20220226-BAN23_B02_B0...,10,ND5.1-on-target,ND5.1-2000-12-rep2-0301,new-lipo2000
1,TSN20220226-010-00090_10_20220226-BAN23_B02_B0...,10,ND5.1-on-target,ND5.1-2000-12-rep2-0301,new-lipo2000
2,TSN20220226-010-00090_11_20220226-BAN23_C02_C0...,11,ND5.1-on-target,untreated-rep1-0301,test
3,TSN20220226-010-00090_11_20220226-BAN23_C02_C0...,11,ND5.1-on-target,untreated-rep1-0301,test
4,TSN20220226-010-00090_12_20220226-BAN23_D02_D0...,12,ND5.1-on-target,untreated-rep2-0301,test
...,...,...,...,...,...
89,TSN20220226-010-00090_7_20220226-BAN23_G01_G01...,7,ND5.1-on-target,UGI-NES-ND5.1-rep1-0301,SupFig22b
90,TSN20220226-010-00090_8_20220226-BAN23_H01_H01...,8,ND5.1-on-target,UGI-NES-ND5.1-rep2-0301,SupFig22b
91,TSN20220226-010-00090_8_20220226-BAN23_H01_H01...,8,ND5.1-on-target,UGI-NES-ND5.1-rep2-0301,SupFig22b
92,TSN20220226-010-00090_9_20220226-BAN23_A02_A02...,9,ND5.1-on-target,ND5.1-2000-12-rep1-0301,new-lipo2000
93,TSN20220226-010-00090_9_20220226-BAN23_A02_A02...,9,ND5.1-on-target,ND5.1-2000-12-rep1-0301,new-lipo2000

0     1
1     2
2     1
3     2
4     1
     ..
89    2
90    1
91    2
92    1
93    2
Name: raw_name, Length: 94, dtype: int64

In [32]:
# df_merge.region_id + '_' + df_merge.lib_name + '_R' + df_merge.raw_name.map(lambda x: x.split('.fq.gz')[0][-1]) + '.fastq.gz'
df_merge['fix_name'] = df_merge.region_id + '_' + df_merge.lib_name + '_R' + df_merge.raw_name.map(lambda x: x.split('.fq.gz')[0][-1]) + '.fastq.gz'
df_merge

,raw_name,idx,region_id,lib_name,anno,fix_name
0,TSN20220226-010-00090_10_20220226-BAN23_B02_B0...,10,ND5.1-on-target,ND5.1-2000-12-rep2-0301,new-lipo2000,ND5.1-on-target_ND5.1-2000-12-rep2-0301_R1.fas...
1,TSN20220226-010-00090_10_20220226-BAN23_B02_B0...,10,ND5.1-on-target,ND5.1-2000-12-rep2-0301,new-lipo2000,ND5.1-on-target_ND5.1-2000-12-rep2-0301_R2.fas...
2,TSN20220226-010-00090_11_20220226-BAN23_C02_C0...,11,ND5.1-on-target,untreated-rep1-0301,test,ND5.1-on-target_untreated-rep1-0301_R1.fastq.gz
3,TSN20220226-010-00090_11_20220226-BAN23_C02_C0...,11,ND5.1-on-target,untreated-rep1-0301,test,ND5.1-on-target_untreated-rep1-0301_R2.fastq.gz
4,TSN20220226-010-00090_12_20220226-BAN23_D02_D0...,12,ND5.1-on-target,untreated-rep2-0301,test,ND5.1-on-target_untreated-rep2-0301_R1.fastq.gz
...,...,...,...,...,...,...
89,TSN20220226-010-00090_7_20220226-BAN23_G01_G01...,7,ND5.1-on-target,UGI-NES-ND5.1-rep1-0301,SupFig22b,ND5.1-on-target_UGI-NES-ND5.1-rep1-0301_R2.fas...
90,TSN20220226-010-00090_8_20220226-BAN23_H01_H01...,8,ND5.1-on-target,UGI-NES-ND5.1-rep2-0301,SupFig22b,ND5.1-on-target_UGI-NES-ND5.1-rep2-0301_R1.fas...
91,TSN20220226-010-00090_8_20220226-BAN23_H01_H01...,8,ND5.1-on-target,UGI-NES-ND5.1-rep2-0301,SupFig22b,ND5.1-on-target_UGI-NES-ND5.1-rep2-0301_R2.fas...
92,TSN20220226-010-00090_9_20220226-BAN23_A02_A02...,9,ND5.1-on-target,ND5.1-2000-12-rep1-0301,new-lipo2000,ND5.1-on-target_ND5.1-2000-12-rep1-0301_R1.fas...
93,TSN20220226-010-00090_9_20220226-BAN23_A02_A02...,9,ND5.1-on-target,ND5.1-2000-12-rep1-0301,new-lipo2000,ND5.1-on-target_ND5.1-2000-12-rep1-0301_R2.fas...

In [35]:
s_cmd = 'mv ' + df_merge['raw_name'] + ' ' + df_merge['fix_name']
s_cmd

0     mv TSN20220226-010-00090_10_20220226-BAN23_B02...
1     mv TSN20220226-010-00090_10_20220226-BAN23_B02...
2     mv TSN20220226-010-00090_11_20220226-BAN23_C02...
3     mv TSN20220226-010-00090_11_20220226-BAN23_C02...
4     mv TSN20220226-010-00090_12_20220226-BAN23_D02...
                            ...
89    mv TSN20220226-010-00090_7_20220226-BAN23_G01_...
90    mv TSN20220226-010-00090_8_20220226-BAN23_H01_...
91    mv TSN20220226-010-00090_8_20220226-BAN23_H01_...
92    mv TSN20220226-010-00090_9_20220226-BAN23_A02_...
93    mv TSN20220226-010-00090_9_20220226-BAN23_A02_...
Length: 94, dtype: object

In [45]:
s_cmd.to_csv('step.01_fastq_rename.sh', index=False, header=False)

In [47]:
with open('step.01_fastq_rename.sh', 'r') as f:
    text = f.read()
    text = text.replace('"', '')

with open('step.01_fastq_rename.sh', 'w') as f:
    f.write(text + '\npigz -p 20 -d *\n')

In [52]:
df

                                             raw_name  idx
0   TSN20220226-010-00090_10_20220226-BAN23_B02_B0...   10
1   TSN20220226-010-00090_10_20220226-BAN23_B02_B0...   10
2   TSN20220226-010-00090_11_20220226-BAN23_C02_C0...   11
3   TSN20220226-010-00090_11_20220226-BAN23_C02_C0...   11
4   TSN20220226-010-00090_12_20220226-BAN23_D02_D0...   12
..                                                ...  ...
89  TSN20220226-010-00090_7_20220226-BAN23_G01_G01...    7
90  TSN20220226-010-00090_8_20220226-BAN23_H01_H01...    8
91  TSN20220226-010-00090_8_20220226-BAN23_H01_H01...    8
92  TSN20220226-010-00090_9_20220226-BAN23_A02_A02...    9
93  TSN20220226-010-00090_9_20220226-BAN23_A02_A02...    9

[94 rows x 2 columns]